version: "3.1"

services:
  db:
    image: postgres:11.14-alpine
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_DATABASE
    ports:
      - 5432:5432
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/data:/var/lib/postgresql/data
  dynamodb:
    image: amazon/dynamodb-local:1.11.477
    ports:
      - 8000:8000
