version: '3'
services:
  postgres:
    image: postgres:10.11
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/data:/var/lib/postgresql/data
